"""GitHub Action integration for CI/CD evaluation.

Posts evaluation results as PR comments and fails builds
on quality regression.
"""

from __future__ import annotations

import json
import os
from typing import Any

import httpx


class GitHubPRReporter:
    """Reports evaluation results to GitHub PRs.

    Posts formatted evaluation reports as PR comments
    and updates commit status.
    """

    def __init__(
        self,
        token: str | None = None,
        repository: str | None = None,
        pr_number: int | None = None,
    ) -> None:
        """Initialize reporter.

        Args:
            token: GitHub API token.
            repository: Repository name (owner/repo).
            pr_number: PR number.
        """
        self.token = token or os.environ.get("GITHUB_TOKEN")
        self.repository = repository or os.environ.get("GITHUB_REPOSITORY")
        self.pr_number = pr_number or self._get_pr_number()

    def _get_pr_number(self) -> int | None:
        """Get PR number from environment."""
        ref = os.environ.get("GITHUB_REF", "")
        # Extract from refs/pull/123/merge
        if "refs/pull/" in ref:
            try:
                return int(ref.split("/")[2])
            except (IndexError, ValueError):
                pass
        return None

    async def post_comment(
        self,
        report: dict[str, Any],
        client: httpx.AsyncClient | None = None,
    ) -> bool:
        """Post evaluation report as PR comment.

        Args:
            report: Evaluation report.
            client: Optional injected httpx client for testing.

        Returns:
            True if successful.
        """
        if not all([self.token, self.repository, self.pr_number]):
            return False

        body = self._format_report(report)
        url = f"https://api.github.com/repos/{self.repository}/issues/{self.pr_number}/comments"

        http = client or httpx.AsyncClient()
        try:
            response = await http.post(
                url,
                headers={
                    "Authorization": f"token {self.token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={"body": body},
            )
            return response.status_code == 201
        finally:
            if client is None:
                await http.aclose()

    def _format_report(self, report: dict[str, Any]) -> str:
        """Format report as markdown.

        Args:
            report: Evaluation report.

        Returns:
            Markdown string.
        """
        lines = [
            "## 🤖 EvalForge Results",
            "",
            f"**Suite:** {report.get('suite_name', 'Unknown')}",
            f"**Backend:** {report.get('backend', 'Unknown')}",
            f"**Duration:** {report.get('duration_seconds', 0):.2f}s",
            "",
        ]

        # Summary
        summary = report.get('summary', {})
        total = summary.get('total_tests', 0)
        passed = summary.get('passed', 0)
        failed = summary.get('failed', 0)

        lines.extend([
            "### Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total Tests | {total} |",
            f"| Passed | {passed} ✅ |",
            f"| Failed | {failed} ❌ |",
            f"| Pass Rate | {summary.get('pass_rate', 0)*100:.1f}% |",
            f"| Avg Score | {summary.get('avg_score', 0):.2f} |",
            "",
        ])

        # Failed tests
        failed_tests = report.get('failed_tests', [])
        if failed_tests:
            lines.extend([
                "### Failed Tests",
                "",
            ])
            for test in failed_tests:
                lines.append(f"- **{test['name']}**: {test.get('error', 'No details')}")
            lines.append("")

        # Judge breakdown
        judge_scores = report.get('judge_scores', {})
        if judge_scores:
            lines.extend([
                "### Judge Performance",
                "",
                "| Judge | Avg Score |",
                "|-------|-----------|",
            ])
            for judge, score in judge_scores.items():
                lines.append(f"| {judge} | {score:.2f} |")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by EvalForge*")

        return "\n".join(lines)

    async def update_commit_status(
        self,
        sha: str,
        state: str,  # success, failure, error, pending
        description: str,
        target_url: str | None = None,
        client: httpx.AsyncClient | None = None,
    ) -> bool:
        """Update commit status.

        Args:
            sha: Commit SHA.
            state: Status state.
            description: Status description.
            target_url: Optional URL with details.
            client: Optional injected httpx client for testing.

        Returns:
            True if successful.
        """
        if not all([self.token, self.repository]):
            return False

        url = f"https://api.github.com/repos/{self.repository}/statuses/{sha}"

        http = client or httpx.AsyncClient()
        try:
            response = await http.post(
                url,
                headers={
                    "Authorization": f"token {self.token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={
                    "state": state,
                    "description": description,
                    "context": "evalforge/evaluation",
                    "target_url": target_url,
                },
            )
            return response.status_code == 201
        finally:
            if client is None:
                await http.aclose()


class RegressionDetector:
    """Detects quality regression from baseline.

    Compares current results to baseline and determines
    if regression is statistically significant.
    """

    def __init__(
        self,
        fail_threshold: float = 0.7,
        regression_threshold: float = 0.1,
    ) -> None:
        """Initialize detector.

        Args:
            fail_threshold: Minimum passing score (0-1).
            regression_threshold: Max allowed regression vs baseline.
        """
        self.fail_threshold = fail_threshold
        self.regression_threshold = regression_threshold

    def check_regression(
        self,
        current: dict[str, Any],
        baseline: dict[str, Any] | None,
    ) -> dict[str, Any]:
        """Check for regression.

        Args:
            current: Current evaluation results.
            baseline: Baseline results (None if first run).

        Returns:
            Regression check result.
        """
        current_score = current.get("summary", {}).get("avg_score", 0)

        # Check absolute threshold
        if current_score < self.fail_threshold:
            return {
                "has_regression": True,
                "reason": f"Score {current_score:.2f} below threshold {self.fail_threshold}",
                "current_score": current_score,
                "threshold": self.fail_threshold,
                "should_fail_build": True,
            }

        # Check vs baseline
        if baseline:
            baseline_score = baseline.get("summary", {}).get("avg_score", current_score)
            regression = baseline_score - current_score

            if regression > self.regression_threshold:
                return {
                    "has_regression": True,
                    "reason": f"Regression of {regression:.2f} vs baseline",
                    "current_score": current_score,
                    "baseline_score": baseline_score,
                    "regression": regression,
                    "should_fail_build": True,
                }

        return {
            "has_regression": False,
            "current_score": current_score,
            "should_fail_build": False,
        }


class CIPipeline:
    """CI/CD pipeline integration.

    Orchestrates evaluation in CI and reports results.
    """

    def __init__(
        self,
        suite_path: str,
        backend: str = "mock",
        fail_threshold: float = 0.7,
    ) -> None:
        """Initialize pipeline.

        Args:
            suite_path: Path to test suite.
            backend: Evaluation backend.
            fail_threshold: Minimum passing score.
        """
        self.suite_path = suite_path
        self.backend = backend
        self.fail_threshold = fail_threshold
        self.reporter = GitHubPRReporter()
        self.regression = RegressionDetector(fail_threshold)

    async def run(self) -> dict[str, Any]:
        """Run CI pipeline.

        Returns:
            Pipeline result.
        """
        # Load suite
        from pathlib import Path

        from evalforge.backends.mock import MockBackend
        from evalforge.backends.openai_compatible import OpenAICompatibleBackend
        from evalforge.loader.suite_loader import SuiteLoader
        from evalforge.runners.rag_runner import RAGRunner
        loader = SuiteLoader()
        suite = loader.load_suite(Path(self.suite_path))

        # Choose backend
        backend: Any = MockBackend()
        if self.backend != "mock":
            backend = OpenAICompatibleBackend()

        # Run evaluation
        runner = RAGRunner(backend=backend)
        results = await runner.run_suite(suite)

        # Build report dict for downstream components
        passed = sum(1 for r in results if r.passed)
        failed = len(results) - passed
        pass_rate = passed / len(results) if results else 0.0
        avg_score = sum(r.score for r in results) / len(results) if results else 0.0

        report = {
            "suite_name": suite.name,
            "backend": self.backend,
            "summary": {
                "total_tests": len(results),
                "passed": passed,
                "failed": failed,
                "pass_rate": pass_rate,
                "avg_score": avg_score,
            },
            "results": [r.model_dump() for r in results],
        }

        # Load baseline
        baseline = await self._load_baseline()

        # Check regression
        regression_result = self.regression.check_regression(report, baseline)

        # Report to GitHub
        await self.reporter.post_comment(report)

        # Update commit status
        sha = os.environ.get("GITHUB_SHA")
        if sha:
            state = "failure" if regression_result["should_fail_build"] else "success"
            await self.reporter.update_commit_status(
                sha,
                state,
                regression_result.get("reason", f"Score: {regression_result['current_score']:.2f}"),
            )

        # Save as new baseline if good
        if not regression_result["has_regression"]:
            await self._save_baseline(report)

        return {
            "evaluation": report,
            "regression_check": regression_result,
            "exit_code": 1 if regression_result["should_fail_build"] else 0,
        }

    async def _load_baseline(self) -> dict[str, Any] | None:
        """Load baseline results.

        Returns:
            Baseline or None.
        """
        baseline_path = ".evalforge/baseline.json"
        if os.path.exists(baseline_path):
            with open(baseline_path) as f:
                data = json.load(f)
                if isinstance(data, dict):
                    return data
        return None

    async def _save_baseline(self, report: dict[str, Any]) -> None:
        """Save current results as baseline.

        Args:
            report: Evaluation report.
        """
        import os
        os.makedirs(".evalforge", exist_ok=True)

        with open(".evalforge/baseline.json", "w") as f:
            json.dump(report, f, indent=2)
